class Collection:
    def __init__(self): ...
    def __len__(self): ...
    def __iter__(self): ...
    def __repr__(self): ...
    def __getitem__(self, index): ...

    def append(self, item: object = ..., /) -> None: ...
    def clear(self) -> None: ...
    def sort(self, reverse=False) -> None: ...
    @property
    def sorted(self) -> bool: ...
